// NOTE: GENERATED FILE //
using Functional;
using System;
using System.Collections.Generic;
using Valigator.Core;
using Valigator.Core.DataContainers.Factories;
using Valigator.Core.DataSources;
using Valigator.Core.StateValidators;
using Valigator.Core.ValueValidators;

namespace Valigator
{
	public static class DefaultedNullableCollectionStateValidatorExtensions
	{
		public static DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TValue, TValue>, Option<TValue>[], Option<TValue>[], TValueValidator> Not<TValue, TValueValidator>(this DefaultedNullableCollectionStateValidator<TValue> source, Func<DefaultedNullableCollectionStateValidator<TValue>, DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TValue, TValue>, Option<TValue>[], Option<TValue>[], TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertOne();

		public static DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSource<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[]> source, Func<DataSource<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[]>, DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertOne();

		public static DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TValue, TValue>, Option<TValue>[], Option<TValue>[], CustomValidator<Option<TValue>[]>> Assert<TValue>(this DefaultedNullableCollectionStateValidator<TValue> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSource<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[]> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TValue, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>> Unique<TValue>(this DefaultedNullableCollectionStateValidator<TValue> source)
			=> source.Add(new UniqueValidator<Option<TValue>>());

		public static DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>> Unique<TSource, TValue>(this DataSource<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[]> source)
			=> source.Add(new UniqueValidator<Option<TValue>>());

		public static DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TValue, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>> ItemCount<TValue>(this DefaultedNullableCollectionStateValidator<TValue> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<Option<TValue>>(minimumItems, maximumItems));

		public static DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>> ItemCount<TSource, TValue>(this DataSource<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[]> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<Option<TValue>>(minimumItems, maximumItems));

		public static DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> ItemCount<TSource, TValue>(this DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<Option<TValue>>(minimumItems, maximumItems));

		public static DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> ItemCount<TSource, TValue>(this DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<Option<TValue>>(minimumItems, maximumItems));

		public static DataSourceStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>> source, Func<DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>>, DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>> source, Func<DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>>, DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceStandardStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, Func<DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>>, DataSourceStandardStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, Func<DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>>, DataSourceInvertedStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, Func<DataSourceStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>>, DataSourceStandardInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, Func<DataSourceInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>>, DataSourceInvertedInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> Unique<TSource, TValue>(this DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>> source)
			=> source.Add(new UniqueValidator<Option<TValue>>());

		public static DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> Unique<TSource, TValue>(this DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>> source)
			=> source.Add(new UniqueValidator<Option<TValue>>());

		public static DataSourceStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>> source, Func<DataSourceStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>>, DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>> source, Func<DataSourceInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>>, DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceStandardStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, Func<DataSourceStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>>, DataSourceStandardStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, Func<DataSourceInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>>, DataSourceInvertedStandardStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, Func<DataSourceStandardInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>>, DataSourceStandardInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, Func<DataSourceInvertedInverted<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>>, DataSourceInvertedInvertedStandard<CollectionNullableDataContainerFactory<DefaultedNullableCollectionStateValidator<TValue>, TSource, TValue>, Option<TValue>[], Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();
	}
}