// NOTE: GENERATED FILE //
using Functional;
using System;
using System.Collections.Generic;
using Valigator.Core;
using Valigator.Core.DataContainers.Factories;
using Valigator.Core.DataSources;
using Valigator.Core.StateValidators;
using Valigator.Core.ValueValidators;

namespace Valigator
{
	public static class NullableOptionalNullableCollectionStateValidatorExtensions
	{
		public static DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], TValueValidator> Not<TValue, TValueValidator>(this NullableOptionalNullableCollectionStateValidator<TValue> source, Func<NullableOptionalNullableCollectionStateValidator<TValue>, DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertOne();

		public static DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSource<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[]> source, Func<DataSource<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[]>, DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertOne();

		public static DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], CustomValidator<Option<TValue>[]>> Assert<TValue>(this NullableOptionalNullableCollectionStateValidator<TValue> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSource<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[]> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>> Unique<TValue>(this NullableOptionalNullableCollectionStateValidator<TValue> source)
			=> source.Add(new UniqueValidator<Option<TValue>>());

		public static DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>> Unique<TSource, TValue>(this DataSource<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[]> source)
			=> source.Add(new UniqueValidator<Option<TValue>>());

		public static DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>> ItemCount<TValue>(this NullableOptionalNullableCollectionStateValidator<TValue> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<Option<TValue>>(minimumItems, maximumItems));

		public static DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>> ItemCount<TSource, TValue>(this DataSource<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[]> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<Option<TValue>>(minimumItems, maximumItems));

		public static DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> ItemCount<TSource, TValue>(this DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<Option<TValue>>(minimumItems, maximumItems));

		public static DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> ItemCount<TSource, TValue>(this DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<Option<TValue>>(minimumItems, maximumItems));

		public static DataSourceStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>> source, Func<DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>>, DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>> source, Func<DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>>, DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceStandardStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, Func<DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>>, DataSourceStandardStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, Func<DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>>, DataSourceInvertedStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, Func<DataSourceStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>>, DataSourceStandardInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>> source, Func<DataSourceInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>>, DataSourceInvertedInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], UniqueValidator<Option<TValue>>, ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> Unique<TSource, TValue>(this DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>> source)
			=> source.Add(new UniqueValidator<Option<TValue>>());

		public static DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> Unique<TSource, TValue>(this DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>> source)
			=> source.Add(new UniqueValidator<Option<TValue>>());

		public static DataSourceStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>> source, Func<DataSourceStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>>, DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>> source, Func<DataSourceInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>>, DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceStandardStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceInvertedInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, CustomValidator<Option<TValue>[]>> Assert<TSource, TValue>(this DataSourceInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, string description, Func<Option<TValue>[], bool> validator)
			=> source.Add(new CustomValidator<Option<TValue>[]>(description, validator));

		public static DataSourceStandardStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, Func<DataSourceStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>>, DataSourceStandardStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, Func<DataSourceInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>>, DataSourceInvertedStandardStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, Func<DataSourceStandardInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>>, DataSourceStandardInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>> source, Func<DataSourceInvertedInverted<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>>, DataSourceInvertedInvertedStandard<OptionalNullableCollectionNullableDataContainerFactory<NullableOptionalNullableCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<Option<TValue>[]>>, Option<TValue>[], ItemCountValidator<Option<TValue>>, UniqueValidator<Option<TValue>>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<Option<TValue>[]>
			=> validatorFactory.Invoke(source).InvertThree();
	}
}