// NOTE: GENERATED FILE //
using Functional;
using System;
using System.Collections.Generic;
using Valigator.Core;
using Valigator.Core.DataContainers.Factories;
using Valigator.Core.DataSources;
using Valigator.Core.StateValidators;
using Valigator.Core.ValueValidators;

namespace Valigator
{
	public static class OptionalCollectionStateValidatorExtensions
	{
		public static DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<TValue[]>>, TValue[], TValueValidator> Not<TValue, TValueValidator>(this OptionalCollectionStateValidator<TValue> source, Func<OptionalCollectionStateValidator<TValue>, DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<TValue[]>>, TValue[], TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertOne();

		public static DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSource<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[]> source, Func<DataSource<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[]>, DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertOne();

		public static DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<TValue[]>>, TValue[], CustomValidator<TValue[]>> Assert<TValue>(this OptionalCollectionStateValidator<TValue> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSource<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[]> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>> Unique<TValue>(this OptionalCollectionStateValidator<TValue> source)
			=> source.Add(new UniqueValidator<TValue>());

		public static DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>> Unique<TSource, TValue>(this DataSource<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[]> source)
			=> source.Add(new UniqueValidator<TValue>());

		public static DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TValue, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>> ItemCount<TValue>(this OptionalCollectionStateValidator<TValue> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<TValue>(minimumItems, maximumItems));

		public static DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>> ItemCount<TSource, TValue>(this DataSource<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[]> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<TValue>(minimumItems, maximumItems));

		public static DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> ItemCount<TSource, TValue>(this DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<TValue>(minimumItems, maximumItems));

		public static DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> ItemCount<TSource, TValue>(this DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>> source, int? minimumItems = null, int? maximumItems = null)
			=> source.Add(new ItemCountValidator<TValue>(minimumItems, maximumItems));

		public static DataSourceStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>> source, Func<DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>>, DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>> source, Func<DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>>, DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceStandardStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceInvertedStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceStandardInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceInvertedInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceStandardStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> source, Func<DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>>, DataSourceStandardStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> source, Func<DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>>, DataSourceInvertedStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> source, Func<DataSourceStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>>, DataSourceStandardInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>> source, Func<DataSourceInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>>, DataSourceInvertedInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], UniqueValidator<TValue>, ItemCountValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> Unique<TSource, TValue>(this DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>> source)
			=> source.Add(new UniqueValidator<TValue>());

		public static DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> Unique<TSource, TValue>(this DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>> source)
			=> source.Add(new UniqueValidator<TValue>());

		public static DataSourceStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>> source, Func<DataSourceStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>>, DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>> source, Func<DataSourceInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>>, DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertTwo();

		public static DataSourceStandardStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceInvertedStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceStandardInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceInvertedInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, CustomValidator<TValue[]>> Assert<TSource, TValue>(this DataSourceInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> source, string description, Func<TValue[], bool> validator)
			=> source.Add(new CustomValidator<TValue[]>(description, validator));

		public static DataSourceStandardStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> source, Func<DataSourceStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>>, DataSourceStandardStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> source, Func<DataSourceInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>>, DataSourceInvertedStandardStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceStandardInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> source, Func<DataSourceStandardInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>>, DataSourceStandardInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertThree();

		public static DataSourceInvertedInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, TValueValidator> Not<TSource, TValue, TValueValidator>(this DataSourceInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>> source, Func<DataSourceInvertedInverted<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>>, DataSourceInvertedInvertedStandard<OptionalNullableCollectionDataContainerFactory<OptionalCollectionStateValidator<TValue>, TSource, TValue>, Optional<Option<TValue[]>>, TValue[], ItemCountValidator<TValue>, UniqueValidator<TValue>, TValueValidator>> validatorFactory)
			where TValueValidator : struct, IValueValidator<TValue[]>
			=> validatorFactory.Invoke(source).InvertThree();
	}
}